// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/v1/rates.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_api_v1_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_rates_proto_rawDescGZIP(), []int{0}
}

func (x *GetRatesRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Ask           string                 `protobuf:"bytes,2,opt,name=ask,proto3" json:"ask,omitempty"`
	Bid           string                 `protobuf:"bytes,3,opt,name=bid,proto3" json:"bid,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_api_v1_rates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_rates_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatesResponse) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *GetRatesResponse) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

func (x *GetRatesResponse) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetRatesResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_v1_rates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_rates_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_v1_rates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_rates_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_v1_rates_proto protoreflect.FileDescriptor

const file_api_v1_rates_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/rates.proto\x12\fgrntx.api.v1\"%\n" +
	"\x0fGetRatesRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\"h\n" +
	"\x10GetRatesResponse\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x10\n" +
	"\x03ask\x18\x02 \x01(\tR\x03ask\x12\x10\n" +
	"\x03bid\x18\x03 \x01(\tR\x03bid\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xad\x01\n" +
	"\fRatesService\x12I\n" +
	"\bGetRates\x12\x1d.grntx.api.v1.GetRatesRequest\x1a\x1e.grntx.api.v1.GetRatesResponse\x12R\n" +
	"\vHealthCheck\x12 .grntx.api.v1.HealthCheckRequest\x1a!.grntx.api.v1.HealthCheckResponseB\x1fZ\x1dgithub.com/qwond/grntx/api/v1b\x06proto3"

var (
	file_api_v1_rates_proto_rawDescOnce sync.Once
	file_api_v1_rates_proto_rawDescData []byte
)

func file_api_v1_rates_proto_rawDescGZIP() []byte {
	file_api_v1_rates_proto_rawDescOnce.Do(func() {
		file_api_v1_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_rates_proto_rawDesc), len(file_api_v1_rates_proto_rawDesc)))
	})
	return file_api_v1_rates_proto_rawDescData
}

var file_api_v1_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_rates_proto_goTypes = []any{
	(*GetRatesRequest)(nil),     // 0: grntx.api.v1.GetRatesRequest
	(*GetRatesResponse)(nil),    // 1: grntx.api.v1.GetRatesResponse
	(*HealthCheckRequest)(nil),  // 2: grntx.api.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: grntx.api.v1.HealthCheckResponse
}
var file_api_v1_rates_proto_depIdxs = []int32{
	0, // 0: grntx.api.v1.RatesService.GetRates:input_type -> grntx.api.v1.GetRatesRequest
	2, // 1: grntx.api.v1.RatesService.HealthCheck:input_type -> grntx.api.v1.HealthCheckRequest
	1, // 2: grntx.api.v1.RatesService.GetRates:output_type -> grntx.api.v1.GetRatesResponse
	3, // 3: grntx.api.v1.RatesService.HealthCheck:output_type -> grntx.api.v1.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_rates_proto_init() }
func file_api_v1_rates_proto_init() {
	if File_api_v1_rates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_rates_proto_rawDesc), len(file_api_v1_rates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_rates_proto_goTypes,
		DependencyIndexes: file_api_v1_rates_proto_depIdxs,
		MessageInfos:      file_api_v1_rates_proto_msgTypes,
	}.Build()
	File_api_v1_rates_proto = out.File
	file_api_v1_rates_proto_goTypes = nil
	file_api_v1_rates_proto_depIdxs = nil
}
